language: node_js
sudo: false
node_js:
  - 'stable'

env:
  global:
    - CODECOV_TOKEN="cf4b16e7-5d70-4996-8807-462317d480a4"

before_script:
  - date --rfc-2822

script:
  - yarn lint
  - yarn pretty
  - yarn spec:coverage
